### PR TITLE
Added user to relevant repositories

### PR DESCRIPTION
**Pull request by PepperMoJ**

### CODE REVIEW

**Review by AntonyBishop — CHANGES_REQUESTED** [review]
Access need to be confirmed by David.Hall@yjb.gov.uk for all YJAF repos. We are not authorise to be the `added_by` on repos we don't own.,

**Review by tamsinforbes — COMMENTED** [review]
I think these ones are missing

yjaf-nginx-gateway
yjaf-refdata
yjaf-returns
yjsm-hub-ui

**Review by andyrogers1973 — APPROVED** [review]
lgtm

**Review by tamsinforbes — COMMENTED** [review]
List of repos looks good - still need the approval from the yjb folks I believe

**Pull request merged**
