### PR TITLE
Rename bichard7 repo

### PR DESCRIPTION
**Pull request by bjpirt**

### CODE REVIEW

**Review by AntonyBishop — CHANGES_REQUESTED** [review]
Hi. Please can you also update `module`. Currently still called "bichard-next-services"

**Review by jakemulley — DISMISSED** [review]

**Review by AntonyBishop — APPROVED** [review]

**Comment by bjpirt** [comment]
@AntonyBishop It looks like the apply failed for this and some of our users have now been locked out of the repos: https://github.com/ministryofjustice/github-collaborators/runs/2858730868

Please could you re-run this?

**Comment by AntonyBishop** [comment]
Hi @bjpirt re-running. I suspect it may fail again as the error is due to MoJ have insufficient "seats" in our Github account. This is being resolved but all changes look to be failing for this reason at the moment.

**Comment by bjpirt** [comment]
@AntonyBishop Thanks for the update - do you know when this might be resolved?

**Comment by AntonyBishop** [comment]
Hi @bjpirt trying to track down an ETA at the moment.

**Comment by bjpirt** [comment]
Thanks Antony

**Pull request merged**
